Repository urlaubsverwaltung/zeiterfassung, pull requests merged in 2022-11, with the labels that each got.

#43 do not show 'week' and 'load more' when there are no time entries yet
  src/main/resources/templates/timeentries/index.html
Labels: status: planned

#46 add padding bottom to _layout content
  src/main/resources/templates/timeentries/_layout.html
Labels: status: planned

#47 fix sticky bottom
  src/main/javascript/components/time-week-header/use-sticky.ts
Labels: status: planned

#38 fix alignment of sticky time-week-header
  src/main/css/style.css
Labels: status: planned, type: bug

#61 Add hint about permissions
  README.md
Labels: status: planned

#63 simplify frontend asset build
  package-lock.json
  package.json
  rollup.config.js
Labels: status: planned, type: enhancement
