Repository urlaubsverwaltung/zeiterfassung, pull requests merged in 2023-10, with the labels that each got.

#416 Remove web based tenant registration
  src/main/java/de/focusshift/zeiterfassung/security/oidc/clientregistration/TenantLifecycleEventHandlerOidcClient.java
  src/main/java/de/focusshift/zeiterfassung/tenancy/registration/TenantRegisteredEvent.java
  src/main/java/de/focusshift/zeiterfassung/tenancy/registration/TenantRegistration.java
  src/main/java/de/focusshift/zeiterfassung/tenancy/registration/TenantRegistrationService.java
  src/main/java/de/focusshift/zeiterfassung/tenancy/registration/messaging/OidcClientRegistrationEventHandlerRabbitmq.java
  src/main/java/de/focusshift/zeiterfassung/tenancy/registration/messaging/OidcClientRegistrationRabbitmqConfiguration.java
  src/main/java/de/focusshift/zeiterfassung/tenancy/registration/property/PropertyTenantInitializer.java
  src/main/java/de/focusshift/zeiterfassung/tenancy/registration/property/TenantRegistryFromOAuthPropertiesImporterService.java
  src/main/java/de/focusshift/zeiterfassung/tenancy/registration/web/TenantRegistration.java
  src/main/java/de/focusshift/zeiterfassung/tenancy/registration/web/TenantRegistrationController.java
  src/main/java/de/focusshift/zeiterfassung/tenancy/registration/web/TenantRegistrationDTO.java
  src/main/resources/templates/tenants/registrations/form.html
  src/main/resources/templates/tenants/registrations/index.html
  src/main/resources/templates/tenants/registrations/successful.html
  src/test/java/de/focusshift/zeiterfassung/tenancy/registration/messaging/OidcClientRegistrationEventHandlerRabbitmqTest.java
Labels: status: planned

#350 Improve logging of ApplicationEventHandlerRabbitmq
  src/main/java/de/focusshift/zeiterfassung/integration/urlaubsverwaltung/application/ApplicationEventHandlerRabbitmq.java
Labels: status: planned, type: enhancement

#424 Increase fraction of csv reports to 3 digits
  src/main/java/de/focusshift/zeiterfassung/report/ReportCsvService.java
  src/test/java/de/focusshift/zeiterfassung/report/ReportCsvServiceTest.java
Labels: status: planned, type: enhancement, topic: report
