Repository urlaubsverwaltung/zeiterfassung, pull requests merged in 2023-07, with the labels that each got.

#298 show sick notes on time entries page
  pom.xml
  src/main/css/1-base.css
  src/main/java/de/focusshift/zeiterfassung/absence/AbsenceColor.java
  src/main/java/de/focusshift/zeiterfassung/absence/AbsenceType.java
  src/main/java/de/focusshift/zeiterfassung/absence/AbsenceWriteEntity.java
  src/main/java/de/focusshift/zeiterfassung/absence/AbsenceWriteService.java
  src/main/java/de/focusshift/zeiterfassung/absence/AbsenceWriteServiceImpl.java
  src/main/java/de/focusshift/zeiterfassung/integration/urlaubsverwaltung/application/ApplicationEventDtoAdapter.java
  src/main/java/de/focusshift/zeiterfassung/integration/urlaubsverwaltung/application/ApplicationEventHandlerRabbitmq.java
  src/main/java/de/focusshift/zeiterfassung/integration/urlaubsverwaltung/application/ApplicationRabbitmqConfiguration.java
  src/main/java/de/focusshift/zeiterfassung/integration/urlaubsverwaltung/application/ApplicationRabbitmqConfigurationProperties.java
  src/main/java/de/focusshift/zeiterfassung/integration/urlaubsverwaltung/sicknote/SickNoteEventDtoAdapter.java
  src/main/java/de/focusshift/zeiterfassung/integration/urlaubsverwaltung/sicknote/SickNoteEventHandlerRabbitmq.java
  src/main/java/de/focusshift/zeiterfassung/integration/urlaubsverwaltung/sicknote/SickNoteRabbitmqConfiguration.java
  src/main/java/de/focusshift/zeiterfassung/tenancy/configuration/multi/AdminAwareDatabaseConfiguration.java
  src/main/resources/db/changelog/changelog-1.6.0-add-absence.xml
  src/main/resources/db/changelog/changelog-1.6.0-fix-tenant-id-length.xml
  src/main/resources/db/changelog/db.changelog-main.xml
  src/main/resources/messages.properties
  src/main/resources/messages_en.properties
Labels: status: planned

#290 show vacations on time-entries page
  docker-compose.yml
  pom.xml
  src/main/css/1-base.css
  src/main/css/reports.css
  src/main/css/time-entries.css
  src/main/java/de/focusshift/zeiterfassung/absence/Absence.java
  src/main/java/de/focusshift/zeiterfassung/absence/AbsenceColor.java
  src/main/java/de/focusshift/zeiterfassung/absence/AbsenceRepository.java
  src/main/java/de/focusshift/zeiterfassung/absence/AbsenceService.java
  src/main/java/de/focusshift/zeiterfassung/absence/AbsenceServiceImpl.java
  src/main/java/de/focusshift/zeiterfassung/absence/AbsenceType.java
  src/main/java/de/focusshift/zeiterfassung/absence/AbsenceWrite.java
  src/main/java/de/focusshift/zeiterfassung/absence/AbsenceWriteEntity.java
  src/main/java/de/focusshift/zeiterfassung/absence/AbsenceWriteService.java
  src/main/java/de/focusshift/zeiterfassung/absence/AbsenceWriteServiceImpl.java
  src/main/java/de/focusshift/zeiterfassung/absence/DayLength.java
  src/main/java/de/focusshift/zeiterfassung/integration/urlaubsverwaltung/application/ApplicationEventDtoAdapter.java
  src/main/java/de/focusshift/zeiterfassung/integration/urlaubsverwaltung/application/ApplicationEventHandlerRabbitmq.java
  src/main/java/de/focusshift/zeiterfassung/integration/urlaubsverwaltung/application/ApplicationRabbitmqConfiguration.java
  src/main/java/de/focusshift/zeiterfassung/integration/urlaubsverwaltung/application/ApplicationRabbitmqConfigurationProperties.java
  src/main/java/de/focusshift/zeiterfassung/integration/urlaubsverwaltung/sicknote/SickNoteEventDtoAdapter.java
  src/main/java/de/focusshift/zeiterfassung/integration/urlaubsverwaltung/sicknote/SickNoteEventHandlerRabbitmq.java
  src/main/java/de/focusshift/zeiterfassung/integration/urlaubsverwaltung/sicknote/SickNoteRabbitmqConfiguration.java
  src/main/java/de/focusshift/zeiterfassung/report/DetailDayAbsenceDto.java
  src/main/java/de/focusshift/zeiterfassung/report/DetailDayDto.java
  src/main/java/de/focusshift/zeiterfassung/report/ReportControllerHelper.java
  src/main/java/de/focusshift/zeiterfassung/report/ReportDay.java
  src/main/java/de/focusshift/zeiterfassung/report/ReportServicePermissionAware.java
  src/main/java/de/focusshift/zeiterfassung/report/ReportServiceRaw.java
  src/main/java/de/focusshift/zeiterfassung/tenancy/configuration/multi/AdminAwareDatabaseConfiguration.java
  src/main/java/de/focusshift/zeiterfassung/timeentry/AbsenceEntryDto.java
  src/main/java/de/focusshift/zeiterfassung/timeentry/ShouldWorkingHours.java
  src/main/java/de/focusshift/zeiterfassung/timeentry/TimeEntryController.java
  src/main/java/de/focusshift/zeiterfassung/timeentry/TimeEntryDay.java
  src/main/java/de/focusshift/zeiterfassung/timeentry/TimeEntryDayDto.java
  src/main/java/de/focusshift/zeiterfassung/timeentry/TimeEntryServiceImpl.java
  src/main/java/de/focusshift/zeiterfassung/timeentry/TimeEntryWeek.java
  src/main/java/de/focusshift/zeiterfassung/timeentry/TimeEntryWeekDto.java
  src/main/resources/application-dev-singletenant.properties
  src/main/resources/application.properties
  src/main/resources/db/changelog/changelog-1.6.0-add-absence.xml
  src/main/resources/db/changelog/changelog-1.6.0-fix-tenant-id-length.xml
  src/main/resources/db/changelog/db.changelog-main.xml
  src/main/resources/messages.properties
  src/main/resources/messages_en.properties
  src/main/resources/templates/reports/user-report-week.html
  src/main/resources/templates/timeentries/index.html
  src/test/java/de/focusshift/zeiterfassung/absence/AbsenceServiceImplTest.java
  src/test/java/de/focusshift/zeiterfassung/absence/AbsenceWriteServiceImplIT.java
  src/test/java/de/focusshift/zeiterfassung/absence/AbsenceWriteServiceImplTest.java
  src/test/java/de/focusshift/zeiterfassung/report/ReportCsvServiceTest.java
  src/test/java/de/focusshift/zeiterfassung/report/ReportDayTest.java
  src/test/java/de/focusshift/zeiterfassung/report/ReportMonthTest.java
  src/test/java/de/focusshift/zeiterfassung/report/ReportServicePermissionAwareTest.java
  src/test/java/de/focusshift/zeiterfassung/report/ReportServiceRawTest.java
  src/test/java/de/focusshift/zeiterfassung/report/ReportWeekTest.java
  src/test/java/de/focusshift/zeiterfassung/timeentry/TimeEntryControllerTest.java
  src/test/java/de/focusshift/zeiterfassung/timeentry/TimeEntryServiceImplTest.java
  src/test/java/de/focusshift/zeiterfassung/timeentry/TimeEntryWeekTest.java
Labels: status: planned

#306 Remove local development properties
  src/main/resources/application.properties
Labels: status: planned

#328 bump @typescript-eslint/* to 6.1.0
  package-lock.json
  package.json
Labels: status: planned, type: dependencies

#326 update absences
  pom.xml
  src/main/java/de/focusshift/zeiterfassung/absence/AbsenceRepository.java
  src/main/java/de/focusshift/zeiterfassung/absence/AbsenceWrite.java
  src/main/java/de/focusshift/zeiterfassung/absence/AbsenceWriteEntity.java
  src/main/java/de/focusshift/zeiterfassung/absence/AbsenceWriteServiceImpl.java
  src/main/java/de/focusshift/zeiterfassung/integration/urlaubsverwaltung/application/ApplicationEventDtoAdapter.java
  src/main/java/de/focusshift/zeiterfassung/integration/urlaubsverwaltung/application/ApplicationEventHandlerRabbitmq.java
  src/main/java/de/focusshift/zeiterfassung/integration/urlaubsverwaltung/sicknote/SickNoteEventDtoAdapter.java
  src/main/java/de/focusshift/zeiterfassung/integration/urlaubsverwaltung/sicknote/SickNoteEventHandlerRabbitmq.java
  src/main/resources/db/changelog/changelog-1.6.2-add-absence-source-id.xml
  src/main/resources/db/changelog/db.changelog-main.xml
  src/test/java/de/focusshift/zeiterfassung/absence/AbsenceWriteServiceImplIT.java
  src/test/java/de/focusshift/zeiterfassung/absence/AbsenceWriteServiceImplTest.java
Labels: status: planned

#329 fix prettier config
  .prettierrc
Labels: javascript, status: planned, type: dependencies

#330 bump svelte
  .eslintrc.js
  package-lock.json
  package.json
  src/main/javascript/components/feedback-heart/FeedbackHeart.svelte
Labels: javascript, status: planned, type: dependencies

#331 use underscores in routing-keys instead of camle-case
  src/main/java/de/focusshift/zeiterfassung/integration/urlaubsverwaltung/application/ApplicationRabbitmqConfiguration.java
  src/main/java/de/focusshift/zeiterfassung/integration/urlaubsverwaltung/application/ApplicationRabbitmqConfigurationProperties.java
Labels: status: planned
