Repository urlaubsverwaltung/zeiterfassung, pull requests merged in 2023-08, with the labels that each got.

#340 Upgrade uv extension api to 0.9.0
  pom.xml
  src/main/java/de/focusshift/zeiterfassung/integration/urlaubsverwaltung/application/ApplicationEventDtoAdapter.java
  src/main/java/de/focusshift/zeiterfassung/integration/urlaubsverwaltung/sicknote/SickNoteEventDtoAdapter.java
Labels: java, status: planned, type: dependencies

#339 Fix absence retrieval for given week
  src/main/java/de/focusshift/zeiterfassung/absence/AbsenceRepository.java
  src/main/java/de/focusshift/zeiterfassung/absence/AbsenceServiceImpl.java
  src/main/java/de/focusshift/zeiterfassung/absence/AbsenceWriteEntity.java
  src/test/java/de/focusshift/zeiterfassung/absence/AbsenceRepositoryIT.java
  src/test/java/de/focusshift/zeiterfassung/absence/AbsenceServiceImplTest.java
  src/test/java/de/focusshift/zeiterfassung/absence/AbsenceWriteServiceImplIT.java
Labels: status: planned

#347 nodejs update
  .nvmrc
  pom.xml
Labels: javascript, status: planned, type: dependencies

#336 Add other absences
  src/main/java/de/focusshift/zeiterfassung/absence/Absence.java
  src/main/java/de/focusshift/zeiterfassung/absence/AbsenceRepository.java
  src/main/java/de/focusshift/zeiterfassung/absence/AbsenceServiceImpl.java
  src/main/java/de/focusshift/zeiterfassung/absence/AbsenceType.java
  src/main/java/de/focusshift/zeiterfassung/absence/AbsenceTypeCategory.java
  src/main/java/de/focusshift/zeiterfassung/absence/AbsenceTypeEntity.java
  src/main/java/de/focusshift/zeiterfassung/absence/AbsenceWriteEntity.java
  src/main/java/de/focusshift/zeiterfassung/absence/AbsenceWriteServiceImpl.java
  src/main/java/de/focusshift/zeiterfassung/integration/urlaubsverwaltung/application/ApplicationEventHandlerRabbitmq.java
  src/main/resources/db/changelog/changelog-1.6.5-add-absence-type-source-id.xml
  src/main/resources/db/changelog/changelog-1.6.5-migrate-existing-absences-with-source-id.xml
  src/main/resources/db/changelog/db.changelog-main.xml
  src/main/resources/messages.properties
  src/main/resources/messages_en.properties
  src/test/java/de/focusshift/zeiterfassung/absence/AbsenceRepositoryIT.java
  src/test/java/de/focusshift/zeiterfassung/absence/AbsenceServiceImplTest.java
  src/test/java/de/focusshift/zeiterfassung/absence/AbsenceTest.java
  src/test/java/de/focusshift/zeiterfassung/absence/AbsenceWriteServiceImplIT.java
  src/test/java/de/focusshift/zeiterfassung/absence/AbsenceWriteServiceImplTest.java
  src/test/java/de/focusshift/zeiterfassung/integration/urlaubsverwaltung/application/ApplicationEventHandlerRabbitmqTest.java
  src/test/java/de/focusshift/zeiterfassung/integration/urlaubsverwaltung/sicknote/SickNoteEventHandlerRabbitmqTest.java
  src/test/java/de/focusshift/zeiterfassung/timeentry/TimeEntryControllerTest.java
Labels: status: planned

#349 Fix to generate avatars on days with only absences
  src/main/java/de/focusshift/zeiterfassung/report/ReportServiceRaw.java
Labels: status: planned

#353 Use PlannedWorkingHours.ZERO if plannedWorkingHours are not available…
  src/main/java/de/focusshift/zeiterfassung/report/ReportServiceRaw.java
Labels: status: planned
