Repository urlaubsverwaltung/zeiterfassung, pull requests merged in 2023-11, with the labels that each got.

#304 Set tenantId to TenantContextHolder via CurrentTenantInterceptor
  src/main/java/de/focusshift/zeiterfassung/tenancy/configuration/multi/TenantContextHolderMultiTenant.java
  src/main/java/de/focusshift/zeiterfassung/tenancy/configuration/single/TenantContextHolderSingleTenant.java
  src/main/java/de/focusshift/zeiterfassung/tenancy/tenant/TenantContextHolder.java
  src/main/java/de/focusshift/zeiterfassung/web/CurrentTenantInterceptor.java
  src/main/java/de/focusshift/zeiterfassung/web/WebConfiguration.java
  src/test/java/de/focusshift/zeiterfassung/tenancy/configuration/multi/TenantContextHolderMultiTenantTest.java
  src/test/java/de/focusshift/zeiterfassung/timeclock/TimeClockControllerTest.java
  src/test/java/de/focusshift/zeiterfassung/web/CurrentTenantInterceptorTest.java
  src/test/java/de/focusshift/zeiterfassung/web/WebConfigurationTest.java
Labels: status: planned, type: enhancement

#439 bump local keycloak to 22.0.4
  docker-compose.yml
Labels: status: planned

#442 fix missing values for AbsenceService methods returning a Map of users
  src/main/java/de/focusshift/zeiterfassung/absence/AbsenceServiceImpl.java
  src/main/java/de/focusshift/zeiterfassung/usermanagement/UserManagementService.java
  src/main/java/de/focusshift/zeiterfassung/usermanagement/UserManagementServiceImpl.java
  src/test/java/de/focusshift/zeiterfassung/absence/AbsenceServiceImplTest.java
  src/test/java/de/focusshift/zeiterfassung/usermanagement/UserManagementServiceImplTest.java
Labels: status: planned

#441 fix duration calculation exact to the minute
  src/main/java/de/focusshift/zeiterfassung/report/DetailDayAbsenceDto.java
  src/main/java/de/focusshift/zeiterfassung/report/DetailDayDto.java
  src/main/java/de/focusshift/zeiterfassung/report/DetailDayEntryDto.java
  src/main/java/de/focusshift/zeiterfassung/report/ReportDay.java
  src/main/java/de/focusshift/zeiterfassung/report/ReportMonth.java
  src/main/java/de/focusshift/zeiterfassung/report/ReportServiceRaw.java
  src/main/java/de/focusshift/zeiterfassung/report/ReportWeek.java
  src/main/java/de/focusshift/zeiterfassung/report/ReportWeekController.java
  src/main/java/de/focusshift/zeiterfassung/timeentry/BreakDuration.java
  src/main/java/de/focusshift/zeiterfassung/timeentry/PlannedWorkingHours.java
  src/main/java/de/focusshift/zeiterfassung/timeentry/ShouldWorkingHours.java
  src/main/java/de/focusshift/zeiterfassung/timeentry/SimpleTimeEntryDuration.java
  src/main/java/de/focusshift/zeiterfassung/timeentry/TimeEntry.java
  src/main/java/de/focusshift/zeiterfassung/timeentry/TimeEntryController.java
  src/main/java/de/focusshift/zeiterfassung/timeentry/TimeEntryDay.java
  src/main/java/de/focusshift/zeiterfassung/timeentry/TimeEntryDuration.java
  src/main/java/de/focusshift/zeiterfassung/timeentry/TimeEntryServiceImpl.java
  src/main/java/de/focusshift/zeiterfassung/timeentry/TimeEntryWeek.java
  src/main/java/de/focusshift/zeiterfassung/timeentry/WorkDuration.java
  src/main/java/de/focusshift/zeiterfassung/timeentry/ZeitDuration.java
  src/main/java/de/focusshift/zeiterfassung/usermanagement/WorkDay.java
  src/test/java/de/focusshift/zeiterfassung/report/ReportDayEntryTest.java
  src/test/java/de/focusshift/zeiterfassung/report/ReportDayTest.java
  src/test/java/de/focusshift/zeiterfassung/report/ReportServiceRawTest.java
  src/test/java/de/focusshift/zeiterfassung/timeentry/BreakDurationTest.java
  src/test/java/de/focusshift/zeiterfassung/timeentry/TimeEntryControllerTest.java
  src/test/java/de/focusshift/zeiterfassung/timeentry/TimeEntryServiceImplTest.java
  src/test/java/de/focusshift/zeiterfassung/timeentry/TimeEntryTest.java
  src/test/java/de/focusshift/zeiterfassung/timeentry/TimeEntryWeekTest.java
  src/test/java/de/focusshift/zeiterfassung/timeentry/WorkDurationTest.java
  src/test/java/de/focusshift/zeiterfassung/timeentry/ZeitDurationTest.java
Labels: status: planned

#443 migrate application properties to yaml
  README.md
  src/main/resources/application-dev-multitenant.properties
  src/main/resources/application-dev-multitenant.yaml
  src/main/resources/application-dev-singletenant.properties
  src/main/resources/application-dev-singletenant.yaml
  src/main/resources/application.properties
  src/main/resources/application.yaml
  src/test/resources/application.properties
  src/test/resources/application.yaml
Labels: status: planned

#449 Fix docker compose example and update to latest version
  .examples/docker-compose/docker-compose.yml
  .examples/docker-compose/keycloak/import/master-realm.json
  .examples/docker-compose/keycloak/import/master-users-0.json
  .examples/docker-compose/keycloak/import/zeiterfassung-realm-realm.json
  .examples/docker-compose/keycloak/import/zeiterfassung-realm-users-0.json
Labels: status: planned

#450 automatically add semicolon in duration input
  .editorconfig
  .github/workflows/build.yml
  package-lock.json
  package.json
  pom.xml
  src/main/javascript/bundles/time-entries.ts
  src/main/javascript/components/time-entry-duration-input/index.ts
  src/main/javascript/components/time-entry-duration-input/time-entry-duration-input.spec.ts
  src/main/javascript/components/time-entry-duration-input/time-entry-duration-input.ts
  src/main/resources/templates/timeentries/index.html
  vitest.config.mjs
Labels: status: planned

#459 Improve release process
  .github/workflows/build.yml
  .github/workflows/release-trigger.yml
  .github/workflows/release.yml
  .mvn/wrapper/MavenWrapperDownloader.java
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
Labels: status: planned, type: enhancement

#462 Only use maven wrapper scripts to recognise maven_args env
  .mvn/wrapper/maven-wrapper.jar
  mvnw
  mvnw.cmd
Labels: status: planned

#463 fix package lock and bump nodes to 20.9.0
  .nvmrc
  package-lock.json
  pom.xml
Labels: javascript, type: dependencies

#469 bump node to 20.10.0
  .nvmrc
  pom.xml
Labels: status: planned

#470 Add favicon
  src/main/java/de/focusshift/zeiterfassung/security/SecurityWebConfiguration.java
  src/main/resources/static/browserconfig.xml
  src/main/resources/static/favicons/android-chrome-192x192.png
  src/main/resources/static/favicons/android-chrome-512x512.png
  src/main/resources/static/favicons/apple-touch-icon.png
  src/main/resources/static/favicons/favicon-16x16.png
  src/main/resources/static/favicons/favicon-32x32.png
  src/main/resources/static/favicons/favicon.ico
  src/main/resources/static/favicons/mstile-150x150.png
  src/main/resources/static/favicons/safari-pinned-tab.svg
  src/main/resources/static/site.webmanifest
  src/main/resources/templates/_layout.html
Labels: status: planned

#464 refactoring: improve UserId / UserLocalId handling
  src/main/java/de/focusshift/zeiterfassung/absence/AbsenceService.java
  src/main/java/de/focusshift/zeiterfassung/absence/AbsenceServiceImpl.java
  src/main/java/de/focusshift/zeiterfassung/report/ReportControllerHelper.java
  src/main/java/de/focusshift/zeiterfassung/report/ReportCsvController.java
  src/main/java/de/focusshift/zeiterfassung/report/ReportDay.java
  src/main/java/de/focusshift/zeiterfassung/report/ReportPermissionService.java
  src/main/java/de/focusshift/zeiterfassung/report/ReportServiceRaw.java
  src/main/java/de/focusshift/zeiterfassung/timeclock/TimeClockService.java
  src/main/java/de/focusshift/zeiterfassung/timeentry/TimeEntry.java
  src/main/java/de/focusshift/zeiterfassung/timeentry/TimeEntryEntity.java
  src/main/java/de/focusshift/zeiterfassung/timeentry/TimeEntryService.java
  src/main/java/de/focusshift/zeiterfassung/timeentry/TimeEntryServiceImpl.java
  src/main/java/de/focusshift/zeiterfassung/user/HasUserIdComposite.java
  src/main/java/de/focusshift/zeiterfassung/user/UserIdComposite.java
  src/main/java/de/focusshift/zeiterfassung/usermanagement/OvertimeAccount.java
  src/main/java/de/focusshift/zeiterfassung/usermanagement/OvertimeAccountController.java
  src/main/java/de/focusshift/zeiterfassung/usermanagement/OvertimeAccountService.java
  src/main/java/de/focusshift/zeiterfassung/usermanagement/OvertimeAccountServiceImpl.java
  src/main/java/de/focusshift/zeiterfassung/usermanagement/User.java
  src/main/java/de/focusshift/zeiterfassung/usermanagement/UserLocalId.java
  src/main/java/de/focusshift/zeiterfassung/usermanagement/UserManagementController.java
  src/main/java/de/focusshift/zeiterfassung/usermanagement/UserManagementService.java
  src/main/java/de/focusshift/zeiterfassung/usermanagement/UserManagementServiceImpl.java
  src/main/java/de/focusshift/zeiterfassung/usermanagement/WorkTimeServiceImpl.java
  src/main/java/de/focusshift/zeiterfassung/usermanagement/WorkWeekUpdate.java
  src/main/java/de/focusshift/zeiterfassung/usermanagement/WorkingTime.java
  src/main/java/de/focusshift/zeiterfassung/usermanagement/WorkingTimeCalendarService.java
  src/main/java/de/focusshift/zeiterfassung/usermanagement/WorkingTimeCalendarServiceImpl.java
  src/main/java/de/focusshift/zeiterfassung/usermanagement/WorkingTimeController.java
  src/main/java/de/focusshift/zeiterfassung/usermanagement/WorkingTimeService.java
  src/test/java/de/focusshift/zeiterfassung/absence/AbsenceServiceImplTest.java
  src/test/java/de/focusshift/zeiterfassung/report/ReportCsvServiceIT.java
  src/test/java/de/focusshift/zeiterfassung/report/ReportCsvServiceTest.java
  src/test/java/de/focusshift/zeiterfassung/report/ReportDayEntryTest.java
  src/test/java/de/focusshift/zeiterfassung/report/ReportDayTest.java
  src/test/java/de/focusshift/zeiterfassung/report/ReportMonthControllerTest.java
  src/test/java/de/focusshift/zeiterfassung/report/ReportMonthTest.java
  src/test/java/de/focusshift/zeiterfassung/report/ReportPermissionServiceTest.java
  src/test/java/de/focusshift/zeiterfassung/report/ReportServiceRawTest.java
  src/test/java/de/focusshift/zeiterfassung/report/ReportWeekControllerTest.java
  src/test/java/de/focusshift/zeiterfassung/report/ReportWeekTest.java
  src/test/java/de/focusshift/zeiterfassung/timeentry/TimeEntryControllerTest.java
  src/test/java/de/focusshift/zeiterfassung/timeentry/TimeEntryServiceImplTest.java
  src/test/java/de/focusshift/zeiterfassung/timeentry/TimeEntryTest.java
  src/test/java/de/focusshift/zeiterfassung/timeentry/TimeEntryWeekTest.java
  src/test/java/de/focusshift/zeiterfassung/usermanagement/OvertimeAccountControllerTest.java
  src/test/java/de/focusshift/zeiterfassung/usermanagement/OvertimeAccountServiceImplTest.java
  src/test/java/de/focusshift/zeiterfassung/usermanagement/UserManagementControllerTest.java
  src/test/java/de/focusshift/zeiterfassung/usermanagement/UserManagementServiceImplTest.java
  src/test/java/de/focusshift/zeiterfassung/usermanagement/WorkTimeServiceImplTest.java
  src/test/java/de/focusshift/zeiterfassung/usermanagement/WorkingTimeCalendarServiceImplTest.java
  src/test/java/de/focusshift/zeiterfassung/usermanagement/WorkingTimeControllerTest.java
  src/test/java/de/focusshift/zeiterfassung/usermanagement/WorkingTimeRepositoryIT.java
Labels: status: planned

#473 Remove deprecated `zeiterfassung.tenant.registration.rabbitmq.routing…
  src/main/java/de/focusshift/zeiterfassung/tenancy/registration/messaging/OidcClientRegistrationRabbitmqConfigurationProperties.java
  src/test/java/de/focusshift/zeiterfassung/tenancy/registration/messaging/OidcClientRegistrationRabbitmqConfigurationPropertiesTest.java
Labels: status: planned

#475 Upgrade postgresql to 16.1
  .examples/docker-compose/docker-compose.yml
  README.md
  docker-compose.yml
  src/test/java/de/focusshift/zeiterfassung/TestContainersBase.java
  src/test/java/de/focusshift/zeiterfassung/TestPostgreSQLContainer.java
  src/test/resources/init-user-db.sql
Labels: status: planned
