Repository urlaubsverwaltung/zeiterfassung, pull requests merged in 2023-01, with the labels that each got.

#84 dependency updates
  .nvmrc
  package-lock.json
  package.json
  pom.xml
Labels: status: planned, type: dependencies

#87 use explicit visible input elements
  src/main/css/style.css
  src/main/resources/templates/timeentries/index.html
Labels: status: planned

#86 Lucide Icon Set
  README.md
  src/main/resources/templates/fragments/feedback-form.html
  src/main/resources/templates/icons/bookmark.html
  src/main/resources/templates/icons/chart-pie.html
  src/main/resources/templates/icons/chevron-left.html
  src/main/resources/templates/icons/chevron-right.html
  src/main/resources/templates/icons/logout.html
  src/main/resources/templates/icons/mail.html
  src/main/resources/templates/icons/paper-airplane.html
  src/main/resources/templates/icons/play.html
  src/main/resources/templates/icons/plus.html
  src/main/resources/templates/icons/refresh.html
  src/main/resources/templates/icons/save.html
  src/main/resources/templates/icons/stop.html
  src/main/resources/templates/icons/trash.html
  src/main/resources/templates/icons/users.html
  src/main/resources/templates/icons/x-circle.html
  src/main/resources/templates/icons/x.html
Labels: status: planned

#50 Add docker compose example
  .editorconfig
  .examples/docker-compose/docker-compose.yml
  docker-compose.yml
  docker/keycloak/keycloak-export/zeiterfassung-realm-realm.json
  src/main/resources/application-dev-singletenant.properties
Labels: status: planned, type: enhancement

#106 Add description about docker-compose setup
  .examples/docker-compose/README.md
  README.md
Labels: topic: documentation, type: enhancement

#88 add option to enter break time-entries
  src/main/css/style.css
  src/main/java/de/focusshift/zeiterfassung/development/DemoDataCreationService.java
  src/main/java/de/focusshift/zeiterfassung/report/ReportCsvService.java
  src/main/java/de/focusshift/zeiterfassung/report/ReportDay.java
  src/main/java/de/focusshift/zeiterfassung/report/ReportDayEntry.java
  src/main/java/de/focusshift/zeiterfassung/report/ReportServiceRaw.java
  src/main/java/de/focusshift/zeiterfassung/timeclock/TimeClockService.java
  src/main/java/de/focusshift/zeiterfassung/timeentry/TimeEntry.java
  src/main/java/de/focusshift/zeiterfassung/timeentry/TimeEntryController.java
  src/main/java/de/focusshift/zeiterfassung/timeentry/TimeEntryDTO.java
  src/main/java/de/focusshift/zeiterfassung/timeentry/TimeEntryEntity.java
  src/main/java/de/focusshift/zeiterfassung/timeentry/TimeEntryServiceImpl.java
  src/main/javascript/components/time-entry-element/TimeEntryElement.ts
  src/main/resources/db/changelog/changelog-1.1.0-add-timeentry-is-break.xml
  src/main/resources/db/changelog/db.changelog-main.xml
  src/main/resources/messages.properties
  src/main/resources/messages_en.properties
  src/main/resources/templates/timeentries/index.html
  src/test/java/de/focusshift/zeiterfassung/report/ReportCsvServiceIT.java
  src/test/java/de/focusshift/zeiterfassung/report/ReportCsvServiceTest.java
  src/test/java/de/focusshift/zeiterfassung/report/ReportDayEntryTest.java
  src/test/java/de/focusshift/zeiterfassung/report/ReportDayTest.java
  src/test/java/de/focusshift/zeiterfassung/report/ReportServiceRawTest.java
  src/test/java/de/focusshift/zeiterfassung/timeclock/TimeClockServiceTest.java
  src/test/java/de/focusshift/zeiterfassung/timeentry/TimeEntryControllerTest.java
  src/test/java/de/focusshift/zeiterfassung/timeentry/TimeEntryRepositoryIT.java
  src/test/java/de/focusshift/zeiterfassung/timeentry/TimeEntryServiceImplTest.java
  src/test/java/de/focusshift/zeiterfassung/timeentry/TimeEntryTest.java
  src/test/java/de/focusshift/zeiterfassung/timeentry/TimeEntryWeekTest.java
Labels: status: planned

#92 edit running time clock
  src/main/css/style.css
  src/main/java/de/focusshift/zeiterfassung/report/ReportController.java
  src/main/java/de/focusshift/zeiterfassung/timeclock/HasTimeClock.java
  src/main/java/de/focusshift/zeiterfassung/timeclock/TimeClock.java
  src/main/java/de/focusshift/zeiterfassung/timeclock/TimeClockController.java
  src/main/java/de/focusshift/zeiterfassung/timeclock/TimeClockControllerAdvice.java
  src/main/java/de/focusshift/zeiterfassung/timeclock/TimeClockDto.java
  src/main/java/de/focusshift/zeiterfassung/timeclock/TimeClockEntity.java
  src/main/java/de/focusshift/zeiterfassung/timeclock/TimeClockMapper.java
  src/main/java/de/focusshift/zeiterfassung/timeclock/TimeClockNotStartedException.java
  src/main/java/de/focusshift/zeiterfassung/timeclock/TimeClockService.java
  src/main/java/de/focusshift/zeiterfassung/timeclock/TimeClockUpdate.java
  src/main/java/de/focusshift/zeiterfassung/timeentry/TimeEntryController.java
  src/main/javascript/bundles/user-common.ts
  src/main/javascript/components/details-dropdown/details-dropdown.ts
  src/main/javascript/components/details-dropdown/index.ts
  src/main/javascript/components/feedback-heart/FeedbackHeart.svelte
  src/main/javascript/components/time-clock/index.ts
  src/main/javascript/components/time-clock/time-clock-edit.ts
  src/main/resources/db/changelog/changelog-1.1.0-add-timeclock-edit.xml
  src/main/resources/db/changelog/db.changelog-main.xml
  src/main/resources/messages.properties
  src/main/resources/messages_en.properties
  src/main/resources/templates/error/4xx.html
  src/main/resources/templates/icons/chevron-down.html
  src/main/resources/templates/icons/edit.html
  src/main/resources/templates/icons/expand.html
  src/main/resources/templates/icons/more-vertical.html
  src/main/resources/templates/timeclock/timeclock-edit-form.html
  src/main/resources/templates/timeclock/timeclock-edit.html
  src/main/resources/templates/timeentries/_navigation.html
  src/test/java/de/focusshift/zeiterfassung/timeclock/TimeClockControllerAdviceTest.java
  src/test/java/de/focusshift/zeiterfassung/timeclock/TimeClockControllerTest.java
  src/test/java/de/focusshift/zeiterfassung/timeclock/TimeClockServiceTest.java
Labels: status: planned

#103 feature edit running time clock with break
  src/main/java/de/focusshift/zeiterfassung/timeclock/TimeClock.java
  src/main/java/de/focusshift/zeiterfassung/timeclock/TimeClockController.java
  src/main/java/de/focusshift/zeiterfassung/timeclock/TimeClockDto.java
  src/main/java/de/focusshift/zeiterfassung/timeclock/TimeClockEntity.java
  src/main/java/de/focusshift/zeiterfassung/timeclock/TimeClockMapper.java
  src/main/java/de/focusshift/zeiterfassung/timeclock/TimeClockService.java
  src/main/java/de/focusshift/zeiterfassung/timeclock/TimeClockUpdate.java
  src/main/resources/messages.properties
  src/main/resources/messages_en.properties
  src/main/resources/templates/timeclock/timeclock-edit-form.html
  src/test/java/de/focusshift/zeiterfassung/timeclock/TimeClockControllerAdviceTest.java
  src/test/java/de/focusshift/zeiterfassung/timeclock/TimeClockControllerTest.java
  src/test/java/de/focusshift/zeiterfassung/timeclock/TimeClockServiceTest.java
Labels: status: planned

#114 add docker image link to release
  .github/workflows/release-trigger.yml
  .github/workflows/release.yml
Labels: status: planned

#115 Add information about docker image to release as external link
  .github/release-notes.yml
  .github/workflows/release.yml
Labels: status: planned

#111 add TimeClock past or present validation
  src/main/java/de/focusshift/zeiterfassung/timeclock/TimeClockDto.java
  src/main/java/de/focusshift/zeiterfassung/timeclock/TimeClockDtoPastOrPresentValidator.java
  src/main/resources/META-INF/services/javax.validation.ConstraintValidator
  src/main/resources/messages.properties
  src/main/resources/messages_en.properties
  src/main/resources/templates/timeclock/timeclock-edit-form.html
  src/test/java/de/focusshift/zeiterfassung/timeclock/TimeClockDtoValidationTest.java
Labels: status: planned

#107 daily sum of hoursWorked
  src/main/css/style.css
  src/main/java/de/focusshift/zeiterfassung/timeentry/TimeEntryController.java
  src/main/java/de/focusshift/zeiterfassung/timeentry/TimeEntryDay.java
  src/main/java/de/focusshift/zeiterfassung/timeentry/TimeEntryDayDto.java
  src/main/java/de/focusshift/zeiterfassung/timeentry/TimeEntryServiceImpl.java
  src/main/java/de/focusshift/zeiterfassung/timeentry/TimeEntryWeek.java
  src/main/java/de/focusshift/zeiterfassung/timeentry/TimeEntryWeekDto.java
  src/main/javascript/bundles/time-entries.ts
  src/main/javascript/components/time-day-header/index.ts
  src/main/javascript/components/time-day-header/time-day-header.ts
  src/main/javascript/components/time-day-header/use-sticky.ts
  src/main/javascript/components/time-week-header/index.ts
  src/main/resources/templates/timeentries/index.html
  src/test/java/de/focusshift/zeiterfassung/timeentry/TimeEntryControllerTest.java
  src/test/java/de/focusshift/zeiterfassung/timeentry/TimeEntryServiceImplTest.java
  src/test/java/de/focusshift/zeiterfassung/timeentry/TimeEntryWeekTest.java
Labels: status: planned

#116 fix responsive time-entry layout
  src/main/css/style.css
  src/main/resources/templates/timeentries/index.html
Labels: status: planned

#117 responsive layout for time-clock edit form
  src/main/css/style.css
  src/main/javascript/components/body-overlay/body-overlay.ts
  src/main/resources/templates/timeclock/timeclock-edit-form.html
  src/main/resources/templates/timeentries/_layout.html
  src/main/resources/templates/timeentries/_navigation.html
Labels: status: planned

#105 introduce launchpad to switch between apps
  README.md
  src/main/css/style.css
  src/main/java/de/focusshift/launchpad/api/HasLaunchpad.java
  src/main/java/de/focusshift/launchpad/api/LaunchpadAppUrlCustomizer.java
  src/main/java/de/focusshift/launchpad/core/App.java
  src/main/java/de/focusshift/launchpad/core/AppDto.java
  src/main/java/de/focusshift/launchpad/core/AppName.java
  src/main/java/de/focusshift/launchpad/core/Launchpad.java
  src/main/java/de/focusshift/launchpad/core/LaunchpadAutoConfiguration.java
  src/main/java/de/focusshift/launchpad/core/LaunchpadConfigProperties.java
  src/main/java/de/focusshift/launchpad/core/LaunchpadControllerAdvice.java
  src/main/java/de/focusshift/launchpad/core/LaunchpadDto.java
  src/main/java/de/focusshift/launchpad/core/LaunchpadService.java
  src/main/java/de/focusshift/launchpad/core/LaunchpadServiceImpl.java
  src/main/java/de/focusshift/zeiterfassung/Application.java
  src/main/java/de/focusshift/zeiterfassung/launchpad/LaunchpadConfiguration.java
  src/main/java/de/focusshift/zeiterfassung/report/ReportController.java
  src/main/java/de/focusshift/zeiterfassung/timeclock/TimeClockController.java
  src/main/java/de/focusshift/zeiterfassung/timeclock/TimeClockEntity.java
  src/main/java/de/focusshift/zeiterfassung/timeentry/TimeEntryController.java
  src/main/resources/application-dev-multitenant.properties
  src/main/resources/application-dev-singletenant.properties
  src/main/resources/application.properties
  src/main/resources/launchpad-core.properties
  src/main/resources/launchpad-core_en.properties
  src/main/resources/templates/launchpad/launchpad.html
  src/main/resources/templates/timeentries/_navigation.html
  src/test/java/de/focusshift/launchpad/core/LaunchpadControllerAdviceIT.java
  src/test/java/de/focusshift/launchpad/core/LaunchpadServiceImplIT.java
  src/test/resources/launchpad-example.properties
Labels: status: planned
