Repository urlaubsverwaltung/zeiterfassung, pull requests merged in 2024-01, with the labels that each got.

#500 add federal state (public holidays) configuration for a person
  .editorconfig
  pom.xml
  src/main/java/de/focusshift/zeiterfassung/publicholiday/FederalState.java
  src/main/java/de/focusshift/zeiterfassung/publicholiday/PublicHoliday.java
  src/main/java/de/focusshift/zeiterfassung/publicholiday/PublicHolidayCalendar.java
  src/main/java/de/focusshift/zeiterfassung/publicholiday/PublicHolidayConfiguration.java
  src/main/java/de/focusshift/zeiterfassung/publicholiday/PublicHolidaysService.java
  src/main/java/de/focusshift/zeiterfassung/publicholiday/PublicHolidaysServiceImpl.java
  src/main/java/de/focusshift/zeiterfassung/usermanagement/WorkingTimeController.java
  src/main/java/de/focusshift/zeiterfassung/usermanagement/WorkingTimeDto.java
  src/main/java/de/focusshift/zeiterfassung/usermanagement/WorkingTimeListEntryDto.java
  src/main/java/de/focusshift/zeiterfassung/web/html/HtmlOptgroupDto.java
  src/main/java/de/focusshift/zeiterfassung/web/html/HtmlOptionDto.java
  src/main/java/de/focusshift/zeiterfassung/web/html/HtmlSelectDto.java
  src/main/java/de/focusshift/zeiterfassung/workingtime/WorkTimeServiceImpl.java
  src/main/java/de/focusshift/zeiterfassung/workingtime/WorkingTime.java
  src/main/java/de/focusshift/zeiterfassung/workingtime/WorkingTimeCalendarServiceImpl.java
  src/main/java/de/focusshift/zeiterfassung/workingtime/WorkingTimeEntity.java
  src/main/java/de/focusshift/zeiterfassung/workingtime/WorkingTimeService.java
  src/main/resources/db/changelog/changelog-0.11.1-add-oidc-registration.xml
  src/main/resources/db/changelog/changelog-0.11.1-add-tenant-user.xml
  src/main/resources/db/changelog/changelog-0.11.1-add-tenant.xml
  src/main/resources/db/changelog/changelog-0.11.1-add-timeclock.xml
  src/main/resources/db/changelog/changelog-0.11.1-add-timeentry.xml
  src/main/resources/db/changelog/changelog-1.1.0-add-timeclock-edit.xml
  src/main/resources/db/changelog/changelog-1.1.0-add-timeentry-is-break.xml
  src/main/resources/db/changelog/changelog-1.1.0-change-type-tenant-id.xml
  src/main/resources/db/changelog/changelog-1.2.0-add-authorities-to-tenant-user.xml
  src/main/resources/db/changelog/changelog-1.2.0-add-working-time.xml
  src/main/resources/db/changelog/changelog-1.2.1-enable-row-level-security-on-working-time.xml
  src/main/resources/db/changelog/changelog-1.4.0-add-overtime-account.xml
  src/main/resources/db/changelog/changelog-1.6.0-add-absence.xml
  src/main/resources/db/changelog/changelog-1.6.0-fix-tenant-id-length.xml
  src/main/resources/db/changelog/changelog-1.6.2-add-absence-source-id.xml
  src/main/resources/db/changelog/changelog-1.6.5-add-absence-type-source-id.xml
  src/main/resources/db/changelog/changelog-1.6.5-migrate-existing-absences-with-source-id.xml
  src/main/resources/db/changelog/changelog-2.0.0-add-federal-state-to-working-time.xml
  src/main/resources/db/changelog/changelog-2.0.0-add-working-time-duration-not-null-constraint.xml
  src/main/resources/db/changelog/changelog-2.0.0-prepare-multiple-working-times-per-user.xml
  src/main/resources/db/changelog/db.changelog-main.xml
  src/main/resources/messages.properties
  src/main/resources/messages_en.properties
  src/main/resources/static/browserconfig.xml
  src/main/resources/templates/fragments/select.html
  src/main/resources/templates/usermanagement/user/working-time-edit.html
  src/main/resources/templates/usermanagement/user/working-time-settings.html
  src/test/java/de/focusshift/zeiterfassung/publicholiday/PublicHolidaysServiceTest.java
  src/test/java/de/focusshift/zeiterfassung/usermanagement/WorkingTimeControllerTest.java
  src/test/java/de/focusshift/zeiterfassung/workingtime/WorkTimeServiceImplTest.java
  src/test/java/de/focusshift/zeiterfassung/workingtime/WorkingTimeCalendarServiceImplTest.java
  src/test/java/de/focusshift/zeiterfassung/workingtime/WorkingTimeRepositoryIT.java
  src/test/resources/logback-test.xml
Labels: status: planned

#539 bump vitest to 1.1.3
  package-lock.json
  package.json
  src/main/javascript/components/form/autosubmit.ts
Labels: javascript, status: planned, type: dependencies

#540 use custom gen_random_uuid function
  src/main/resources/db/changelog/changelog-2.0.0-prepare-multiple-working-times-per-user.xml
Labels: status: planned, type: bug

#541 Add footer
  src/main/java/de/focusshift/zeiterfassung/footer/FooterConfiguration.java
  src/main/java/de/focusshift/zeiterfassung/footer/FooterControllerAdvice.java
  src/main/resources/application.yaml
  src/main/resources/templates/_footer.html
  src/main/resources/templates/_layout.html
  src/test/java/de/focusshift/zeiterfassung/footer/FooterConfigurationTest.java
  src/test/java/de/focusshift/zeiterfassung/footer/FooterControllerAdviceTest.java
  src/test/resources/application.yaml
Labels: status: planned

#542 Do use MissingClaimAuthorityException in group claim mapper...
  src/main/java/de/focusshift/zeiterfassung/security/oidc/claimmapper/RolesFromGroupsClaimMapper.java
  src/test/java/de/focusshift/zeiterfassung/security/oidc/claimmapper/RolesFromGroupsClaimMapperTest.java
Labels: status: planned, topic: oidc, type: bug

#549 Rename web mvc configurer bean of footer
  src/main/java/de/focusshift/zeiterfassung/footer/FooterConfiguration.java
Labels: status: planned

#569 fix person search input glitch after navigating to other user-settings-page
  src/main/resources/templates/usermanagement/users.html
Labels: status: planned
