Repository urlaubsverwaltung/zeiterfassung, pull requests merged in 2024-12, with the labels that each got.

#988 public holidays: add parts of the us
  src/main/java/de/focusshift/zeiterfassung/publicholiday/FederalState.java
  src/main/java/de/focusshift/zeiterfassung/publicholiday/PublicHolidayConfiguration.java
  src/main/resources/messages.properties
  src/main/resources/messages_en.properties
  src/test/java/de/focusshift/zeiterfassung/publicholiday/PublicHolidayConfigurationTest.java
Labels: status: planned

#992 Testcontainer keycloak 26.0.6
  .examples/docker-compose/docker-compose.yml
  .examples/docker-compose/keycloak/import/master-realm.json
  .examples/docker-compose/keycloak/import/master-users-0.json
  docker-compose.yml
  docker/keycloak/export/master-realm.json
  docker/keycloak/export/master-users-0.json
  src/test/java/de/focusshift/zeiterfassung/TestKeycloakContainer.java
Labels: status: planned

#993 bump node to 22.12.0
  .nvmrc
  .tool-versions
  pom.xml
Labels: javascript, status: planned, type: dependencies

#1016 logback: upgrade to 1.5.14
  pom.xml
Labels: java, status: planned, type: dependencies

#1002 First version of daylightsaving time issue
  src/main/java/de/focusshift/zeiterfassung/absence/Absence.java
  src/main/java/de/focusshift/zeiterfassung/absence/AbsenceServiceImpl.java
  src/main/java/de/focusshift/zeiterfassung/workingtime/WorkingTimeCalendarServiceImpl.java
  src/test/java/de/focusshift/zeiterfassung/absence/AbsenceIT.java
  src/test/java/de/focusshift/zeiterfassung/absence/AbsenceServiceImplTest.java
  src/test/java/de/focusshift/zeiterfassung/integration/urlaubsverwaltung/sicknote/SickNoteEventHandlerRabbitmqIT.java
  src/test/java/de/focusshift/zeiterfassung/report/ReportDayTest.java
  src/test/java/de/focusshift/zeiterfassung/report/ReportWeekControllerTest.java
  src/test/java/de/focusshift/zeiterfassung/timeentry/TimeEntryControllerTest.java
  src/test/java/de/focusshift/zeiterfassung/workingtime/WorkingTimeCalendarServiceImplTest.java
Labels: status: planned
