Repository urlaubsverwaltung/zeiterfassung, pull requests merged in 2024-10, with the labels that each got.

#865 Sum of daily work on reports week as duration
  src/main/java/de/focusshift/zeiterfassung/report/DetailDayDto.java
  src/main/java/de/focusshift/zeiterfassung/report/ReportControllerHelper.java
  src/main/java/de/focusshift/zeiterfassung/web/DurationFormatter.java
  src/main/resources/messages.properties
  src/main/resources/messages_en.properties
  src/main/resources/templates/reports/user-report-week.html
  src/test/java/de/focusshift/zeiterfassung/report/ReportWeekControllerTest.java
  src/test/java/de/focusshift/zeiterfassung/web/DurationFormatterTest.java
Labels: status: planned

#874 Summary of planned / worked and delta hours
  src/main/css/reports.css
  src/main/java/de/focusshift/zeiterfassung/report/DetailDayDto.java
  src/main/java/de/focusshift/zeiterfassung/report/GraphMonthDto.java
  src/main/java/de/focusshift/zeiterfassung/report/GraphWeekDto.java
  src/main/java/de/focusshift/zeiterfassung/report/ReportControllerHelper.java
  src/main/java/de/focusshift/zeiterfassung/report/ReportDay.java
  src/main/java/de/focusshift/zeiterfassung/report/ReportMonth.java
  src/main/java/de/focusshift/zeiterfassung/report/ReportMonthController.java
  src/main/java/de/focusshift/zeiterfassung/report/ReportWeek.java
  src/main/java/de/focusshift/zeiterfassung/timeentry/HasWorkedHoursRatio.java
  src/main/java/de/focusshift/zeiterfassung/timeentry/ShouldWorkingHours.java
  src/main/java/de/focusshift/zeiterfassung/timeentry/TimeEntryDay.java
  src/main/java/de/focusshift/zeiterfassung/timeentry/TimeEntryServiceImpl.java
  src/main/java/de/focusshift/zeiterfassung/timeentry/TimeEntryWeek.java
  src/main/java/de/focusshift/zeiterfassung/timeentry/WorkDuration.java
  src/main/java/de/focusshift/zeiterfassung/user/DateFormatter.java
  src/main/java/de/focusshift/zeiterfassung/user/DateFormatterImpl.java
  src/main/java/de/focusshift/zeiterfassung/user/DateRangeFormatter.java
  src/main/java/de/focusshift/zeiterfassung/workingtime/PlannedWorkingHours.java
  src/main/resources/messages.properties
  src/main/resources/messages_en.properties
  src/main/resources/templates/reports/user-report-month.html
  src/main/resources/templates/reports/user-report-week.html
  src/main/resources/templates/reports/user-report.html
  src/test/java/de/focusshift/zeiterfassung/report/ReportMonthControllerTest.java
  src/test/java/de/focusshift/zeiterfassung/report/ReportServiceRawTest.java
  src/test/java/de/focusshift/zeiterfassung/report/ReportWeekControllerTest.java
  src/test/java/de/focusshift/zeiterfassung/timeentry/HasWorkedHoursRatioTest.java
Labels: status: planned

#888 Add some missing i18n
  src/main/resources/messages.properties
  src/main/resources/messages_en.properties
  src/main/resources/templates/_navigation.html
  src/main/resources/templates/usermanagement/user/working-time-edit.html
  src/main/resources/templates/usermanagement/user/working-time-settings.html
Labels: status: planned

#889 567 report break icon
  src/main/java/de/focusshift/zeiterfassung/report/DetailDayEntryDto.java
  src/main/java/de/focusshift/zeiterfassung/report/ReportControllerHelper.java
  src/main/resources/templates/icons/coffee.html
  src/main/resources/templates/reports/user-report-week.html
Labels: status: planned

#890 Bei nicht vorhandenem Kommentar soll ein Icon angezeigt werden welches dieses symbolisiert
  src/main/resources/templates/icons/message-circle-off.html
  src/main/resources/templates/reports/user-report-week.html
Labels: status: planned, type: enhancement, topic: report

#891 bump node to 22.10.0
  .nvmrc
  .tool-versions
  pom.xml
Labels: javascript, status: planned, type: dependencies

#892 show selected persons on report view
  package-lock.json
  package.json
  src/main/css/1-base.css
  src/main/css/2-components.css
  src/main/css/components/avatar-group.css
  src/main/css/components/tooltip.css
  src/main/css/reports.css
  src/main/java/de/focusshift/zeiterfassung/report/ReportControllerHelper.java
  src/main/javascript/components/avatar/avatar.ts
  src/main/javascript/components/tooltip/index.ts
  src/main/javascript/components/tooltip/tooltip.spec.ts
  src/main/javascript/components/tooltip/tooltip.ts
  src/main/resources/templates/_navigation.html
  src/main/resources/templates/fragments/avatar.html
  src/main/resources/templates/icons/ellipsis.html
  src/main/resources/templates/reports/_user-select.html
  src/main/resources/templates/reports/user-report-month.html
  src/main/resources/templates/reports/user-report-week.html
  tailwind.config.js
Labels: status: planned

#912 Fix duration for timeentry which ends next day
  src/main/java/de/focusshift/zeiterfassung/report/DetailDayEntryDto.java
  src/test/java/de/focusshift/zeiterfassung/report/DetailDayEntryDtoTest.java
Labels: status: planned

#913 Fix missing rendering in month chart for work hours >= should hours
  src/main/resources/templates/reports/user-report-month.html
Labels: status: planned

#921 Automatically add selected users on month and week navigation if not …
  src/main/resources/templates/reports/user-report.html
Labels: status: planned

#915 improved i18n for the report view for worked hours
  src/main/resources/messages.properties
  src/main/resources/messages_en.properties
  src/main/resources/templates/reports/user-report-month.html
  src/main/resources/templates/reports/user-report-week.html
  src/main/resources/templates/timeentries/index.html
Labels: status: planned

#922 Make shouldWorkingHours implementation aware of multiple users
  src/main/java/de/focusshift/zeiterfassung/report/ReportDay.java
  src/test/java/de/focusshift/zeiterfassung/report/ReportDayTest.java
Labels: status: planned
