Repository urlaubsverwaltung/zeiterfassung, pull requests merged in 2024-11, with the labels that each got.

#931 fix report planned vs should workingtime
  src/main/java/de/focusshift/zeiterfassung/absence/DayLength.java
  src/main/java/de/focusshift/zeiterfassung/report/ReportControllerHelper.java
  src/main/java/de/focusshift/zeiterfassung/report/ReportDay.java
  src/main/java/de/focusshift/zeiterfassung/report/ReportServiceRaw.java
  src/main/java/de/focusshift/zeiterfassung/timeentry/TimeEntryServiceImpl.java
  src/main/java/de/focusshift/zeiterfassung/workingtime/WorkingTimeCalendar.java
  src/main/java/de/focusshift/zeiterfassung/workingtime/WorkingTimeCalendarServiceImpl.java
  src/test/java/de/focusshift/zeiterfassung/report/ReportCsvServiceTest.java
  src/test/java/de/focusshift/zeiterfassung/report/ReportDayTest.java
  src/test/java/de/focusshift/zeiterfassung/report/ReportMonthControllerTest.java
  src/test/java/de/focusshift/zeiterfassung/report/ReportMonthTest.java
  src/test/java/de/focusshift/zeiterfassung/report/ReportServiceRawTest.java
  src/test/java/de/focusshift/zeiterfassung/report/ReportWeekControllerTest.java
  src/test/java/de/focusshift/zeiterfassung/report/ReportWeekTest.java
  src/test/java/de/focusshift/zeiterfassung/timeentry/TimeEntryServiceImplTest.java
  src/test/java/de/focusshift/zeiterfassung/workingtime/WorkingTimeCalendarServiceImplTest.java
  src/test/java/de/focusshift/zeiterfassung/workingtime/WorkingTimeCalendarTest.java
Labels: status: planned

#906 add aggregated info of selected users to report view
  src/main/css/reports.css
  src/main/java/de/focusshift/zeiterfassung/report/DeltaWorkingHours.java
  src/main/java/de/focusshift/zeiterfassung/report/HasWorkDurationByUser.java
  src/main/java/de/focusshift/zeiterfassung/report/ReportControllerHelper.java
  src/main/java/de/focusshift/zeiterfassung/report/ReportDay.java
  src/main/java/de/focusshift/zeiterfassung/report/ReportDayEntry.java
  src/main/java/de/focusshift/zeiterfassung/report/ReportFunctions.java
  src/main/java/de/focusshift/zeiterfassung/report/ReportMonth.java
  src/main/java/de/focusshift/zeiterfassung/report/ReportMonthController.java
  src/main/java/de/focusshift/zeiterfassung/report/ReportSelectedUserDurationAggregationDto.java
  src/main/java/de/focusshift/zeiterfassung/report/ReportServiceRaw.java
  src/main/java/de/focusshift/zeiterfassung/report/ReportWeek.java
  src/main/java/de/focusshift/zeiterfassung/report/ReportWeekController.java
  src/main/java/de/focusshift/zeiterfassung/timeentry/TimeEntry.java
  src/main/javascript/components/avatar/avatar.ts
  src/main/resources/messages.properties
  src/main/resources/messages_en.properties
  src/main/resources/templates/reports/user-report.html
  src/test/java/de/focusshift/zeiterfassung/report/ReportDayTest.java
  src/test/java/de/focusshift/zeiterfassung/report/ReportMonthControllerTest.java
  src/test/java/de/focusshift/zeiterfassung/report/ReportServiceRawTest.java
  src/test/java/de/focusshift/zeiterfassung/report/ReportWeekControllerTest.java
Labels: status: planned

#943 bump node to 22.11.0
  .nvmrc
  .tool-versions
  pom.xml
Labels: javascript, status: planned, type: dependencies

#949 fix FeedbackHear / migrate to svelte5
  rollup.config.mjs
  src/main/javascript/components/feedback-heart/FeedbackHeart.svelte
  src/main/javascript/components/feedback-heart/feedbackHeartView.ts
Labels: status: planned

#946 fix broken javascript in safari
  .github/workflows/build.yml
  pom.xml
  src/main/resources/templates/_layout.html
  src/test/java/de/focusshift/zeiterfassung/RabbitTestConfiguration.java
  src/test/java/de/focusshift/zeiterfassung/ui/extension/PlaywrightTraceExtension.java
  src/test/java/de/focusshift/zeiterfassung/ui/extension/TestRecordVideoExtension.java
  src/test/java/de/focusshift/zeiterfassung/ui/extension/UiTest.java
Labels: status: planned

#962 Run UI tests on trigger release workflow
  .github/workflows/build.yml
  .github/workflows/release-trigger.yml
Labels: status: planned

#963 [workflow] only run "Upload artifacts of failed tests" step if files …
  .github/workflows/build.yml
  .github/workflows/release-trigger.yml
Labels: status: planned, type: enhancement

#971 fix avatar initials for usernames with whitespace
  src/main/java/de/focusshift/zeiterfassung/avatar/AvatarController.java
  src/main/java/de/focusshift/zeiterfassung/tenancy/user/TenantUserServiceImpl.java
  src/main/resources/db/changelog/changelog-2.14.0-remove-leading-trailing-whitespaces-username.xml
  src/main/resources/db/changelog/db.changelog-main.xml
  src/test/java/de/focusshift/zeiterfassung/avatar/AvatarControllerTest.java
  src/test/java/de/focusshift/zeiterfassung/tenancy/user/TenantUserServiceImplTest.java
Labels: status: planned
