Repository urlaubsverwaltung/zeiterfassung, pull requests merged in 2025-08, with the labels that each got.

#1466 enable locking of time entries by default
  src/main/resources/db/changelog/changelog-2.23.4-locking-time-entries-default-to-true.xml
  src/main/resources/db/changelog/db.changelog-main.xml
Labels: status: planned

#1475 remove workingTime validation criteria since empty is valid state
  src/main/java/de/focusshift/zeiterfassung/usermanagement/WorkingTimeController.java
  src/main/java/de/focusshift/zeiterfassung/usermanagement/WorkingTimeDto.java
  src/main/java/de/focusshift/zeiterfassung/usermanagement/WorkingTimeDtoValidator.java
  src/main/java/de/focusshift/zeiterfassung/workingtime/WorkTimeServiceImpl.java
  src/main/java/de/focusshift/zeiterfassung/workingtime/WorkingTime.java
  src/main/resources/messages.properties
  src/main/resources/messages_en.properties
  src/main/resources/templates/usermanagement/user/working-time-edit.html
  src/test/java/de/focusshift/zeiterfassung/usermanagement/WorkingTimeControllerTest.java
  src/test/java/de/focusshift/zeiterfassung/usermanagement/WorkingTimeDtoValidatorTest.java
  src/test/java/de/focusshift/zeiterfassung/workingtime/WorkTimeServiceImplTest.java
Labels: status: planned

#1477 Update maven wrapper to version 3.9.11
  .mvn/wrapper/maven-wrapper.properties
Labels: java, status: planned, type: dependencies, dependencies

#1487 settings page: fix settings preview param
  src/main/javascript/bundles/settings.ts
  src/test/java/de/focusshift/zeiterfassung/ui/SettingsUIIT.java
  src/test/java/de/focusshift/zeiterfassung/ui/pages/SettingsPage.java
Labels: status: planned, type: bug
