Repository urlaubsverwaltung/zeiterfassung, pull requests merged in 2025-01, with the labels that each got.

#1023 fix calculation of calendar weeks
  src/main/java/de/focusshift/zeiterfassung/report/ReportControllerHelper.java
  src/main/java/de/focusshift/zeiterfassung/report/ReportWeek.java
  src/main/java/de/focusshift/zeiterfassung/timeentry/TimeEntryController.java
  src/main/java/de/focusshift/zeiterfassung/timeentry/TimeEntryWeek.java
  src/main/java/de/focusshift/zeiterfassung/user/UserDateServiceImpl.java
  src/test/java/de/focusshift/zeiterfassung/report/ReportWeekTest.java
  src/test/java/de/focusshift/zeiterfassung/timeentry/TimeEntryControllerTest.java
  src/test/java/de/focusshift/zeiterfassung/timeentry/TimeEntryWeekTest.java
  src/test/java/de/focusshift/zeiterfassung/user/UserDateServiceImplTest.java
Labels: status: planned

#1031 Full resource claim mapper for launchpad with authority match
  src/main/java/de/focusshift/zeiterfassung/security/oidc/claimmapper/RolesFromFullResourceAccessClaimMapper.java
  src/test/java/de/focusshift/zeiterfassung/security/oidc/claimmapper/RolesFromFullResourceAccessClaimMapperTest.java
Labels: status: planned

#1059 Readme: operations
  README.md
Labels: status: planned, type: enhancement

#1060 bump node to 22.13.1
  .nvmrc
  .tool-versions
  pom.xml
Labels: javascript, status: planned, type: dependencies
