Repository urlaubsverwaltung/zeiterfassung, pull requests merged in 2025-04, with the labels that each got.

#1216 bump eslint from 8 to 9
  .eslintrc.js
  eslint.config.mjs
  package-lock.json
  package.json
  tsconfig.json
Labels: status: planned

#1229 Rename "Zeitslots" to "Zeiteintrag"
  src/main/resources/messages.properties
  src/main/resources/messages_en.properties
  src/main/resources/templates/timeentries/fragments/time-entry-dialog.html
  src/main/resources/templates/timeentries/index.html
Labels: status: planned

#241 Add help to avatar menu
  src/main/java/de/focusshift/zeiterfassung/user/FrameDataProvider.java
  src/main/java/de/focusshift/zeiterfassung/web/MenuProperties.java
  src/main/resources/messages.properties
  src/main/resources/messages_en.properties
  src/main/resources/templates/_navigation.html
  src/main/resources/templates/icons/external-link.html
  src/main/resources/templates/icons/help-circle.html
  src/test/java/de/focusshift/zeiterfassung/timeclock/TimeClockControllerTest.java
  src/test/java/de/focusshift/zeiterfassung/web/MenuPropertiesTest.java
Labels: status: planned, type: enhancement

#1251 Replace with spring changelog generator
  .github/workflows/release-trigger.yml
  .github/workflows/release.yml
Labels: status: planned

#1258 fix ui issues
  src/main/css/2-components.css
  src/main/css/time-entries.css
  src/main/resources/templates/fragments/select.html
  src/main/resources/templates/usermanagement/user/overtime-account-settings.html
  src/main/resources/templates/usermanagement/user/working-time-edit.html
Labels: status: planned

#1276 bump node to 22.15.0
  .nvmrc
  .tool-versions
  pom.xml
Labels: javascript, status: planned, dependencies
